#! /bin/sh

# Settings
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width        	4
bspc config normal_border_color 	'#282A36'
bspc config focused_border_color 	'#D69666'
bspc config window_gap          	8
bspc config click_to_focus		true
bspc config focus_follows_pointer	true
bspc config pointer_follows_monitor	true
bspc config presel_feedback_color	'#50FA7B'

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle true

# Rules
bspc rule -a '*:zathura'                  state=tiled
bspc rule -a '*:keepassx'                 state=floating

# Autostart
sxhkd &
killall -p dunst
dunst & 
~/.fehbg &
~/.config/polybar/launch.sh &
compton &
# redshift
