#! /bin/sh

sxhkd &

# Settings
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width        	2
bspc config normal_border_color 	'#282A36'
bspc config focused_border_color 	'#F1FA8C'
bspc config window_gap          	6
bspc config click_to_focus		true
bspc config focus_follows_pointer	true
bspc config pointer_follows_monitor	true
bspc config presel_feedback_color	'#50FA7B'

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules
bspc rule -a '*:keepassxc'	state=floating
bspc rule -a '*:zathura'	state=tiled
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Autostart
killall -p dunst
dunst & 
~/.fehbg &
$HOME/.config/polybar/launch.sh
